Repository HYF-Class19/workflow-group-4, pull requests merged in 2022-07, with the labels that each got.

#8 thomas-ayissi: group4-bio version2
  students-bio/README.md
  students-bio/img/pic-thomas.jpeg
  students-bio/thomas-group4-bio.md
Labels: md, student-bio-group-4

#12 created md file in new branch my-bio
  students-bio/README.md
  students-bio/lemma-barnabas.md
Labels: md

#10 add my bio
  .cspell.json
  students-bio/README.md
  students-bio/podnesTaF.md
Labels: md

#17 Oleksii bio version 2
  .cspell.json
  package.json
  students-bio/podnes.md
Labels: md

#18 Nashmiab.bio
  students-bio/README.md
  students-bio/img/nash.m.jpg
  students-bio/img/nash.t.jpg
  students-bio/nashmiab-bio.md
Labels: md

#16 Bibha
  .cspell.json
  students-bio/README.md
  students-bio/bibhasingh-bio.md
  students-bio/img/bibha.png
Labels: md, student-bio-group-4

#21 added anas student bio & readme
  students-bio/README.md
  students-bio/anas.md
Labels: md, student-bio-group-4

#22 Main/draft for solve conflicts thomas ayissi please dont push here
  .cspell.json
  .gitignore
  .ls-lint.yml
  .vscode/settings.json
  package-lock.json
  package.json
Labels: bug, solving bugs in our master branch

#24 Group4 readme file 21july version : put the content of our "read me" file in the right place
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workflow-group-4-correct-repo.iml
  README.md
  students-bio/thomas-group4-bio.md
Labels: student-bio-group-4, week2

#26 thomas-ayissi: intro file and folder people creating -week2 individual work
  .idea/misc.xml
  README.md
  people/intro-from-thomas-ayissi-group-four.md
Labels: md, week2, intro-file-week2-for-people-folder

#28 thomas-ayissi: GitHub pages group4 - update home page - Https/GitHub.com/hyf class19/workflow group 4/pull/8
  .cspell.json
  .gitignore
  .ls-lint.yml
  README.md
Labels: week2, WebSite Group4 - Github Pages

#30 thomas-ayissi: Github Pages - Small Update - Https/GitHub.com/hyf class19/workflow group 4/pull/8
  .cspell.json
  .ls-lint.yml
  README.md
Labels: week2, WebSite Group4 - Github Pages
